[package]
name = "taskd"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "3.3.3"
dotenv = "0.15.0"
tracing = "0.1.29"
tracing-subscriber = "0.3.6"
tokio = { version = "1.18.4", features = ["rt", "sync", "time", "macros"] }
